# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Trigger workflow for auto-release of CSM projects
name: Auto-Trigger Release of CSM go libs

on:
  workflow_dispatch:

jobs:
  release_independent_repos:
    name: Release Independent Go Libraries
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: [
            # "khareRajshree/goiscsi",
            # "khareRajshree/gonvme",
            # "khareRajshree/gocsi",
            # "khareRajshree/gofsutil",
            # "khareRajshree/gopowerstore",
            # "khareRajshree/gopowerscale",
            # "khareRajshree/gopowermax",
            # "khareRajshree/gounity",
            # "khareRajshree/goscaleio",
            # "khareRajshree/goobjectscale",
            # "khareRajshree/dell-csi-extensions",
            ""mgandharva/test-dell-csi-extensions,
          ]
    steps:
      - name: Trigger Release of ${{ matrix.repo }}
        id: release
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: release-go-libs
          client-payload: |
            { 
              "ref": "${{ github.ref }}", 
              "sha": "${{ github.sha }}"
            }

  # release_dependent_repo:
  #   name: Release Dependent Go Libraries
  #   runs-on: ubuntu-latest
  #   needs: [release_independent_repos]
  #   strategy:
  #     matrix:
  #       repo:
  #         [
  #           "khareRajshree/gobrick",
  #           "khareRajshree/csi-metadata-retriever",
  #           "khareRajshree/csi-volumegroup-snapshotter",
  #         ]
  #   steps:
  #     - name: Trigger Release of ${{ matrix.repo }}
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         repository: ${{ matrix.repo }}
  #         event-type: release-go-libs
  #         client-payload: |
  #           {
  #             "ref": "${{ github.ref }}",
  #             "sha": "${{ github.sha }}"
  #           }
