# Copyright (c) 2024 Dell Inc., or its subsidiaries. All Rights Reserved.
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
#  http://www.apache.org/licenses/LICENSE-2.0

# Trigger workflow for auto-release of CSM projects
name: Auto-Trigger Release of CSM go libs

on:
  workflow_dispatch:

jobs:
  release_independent_repos:
    name: Release goiscsi and gonvme
    runs-on: ubuntu-latest
    strategy:
      matrix:
        repo: ["khareRajshree/goiscsi", "khareRajshree/gonvme"]
    steps:
      - name: Trigger Release of ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: release-go-libs
          client-payload: |
            { 
              "ref": "${{ github.ref }}", 
              "sha": "${{ github.sha }}"
            }

  # update_dependencies:
  #   # uses: khareRajshree/common-github-actions/.github/workflows/update-libraries-to-commits.yml@main
  #   # secrets: inherit
  #   name: Update Dell Packages to Latest Commits
  #   runs-on: ubuntu-latest
  #   needs: release_independent_repos

  #   strategy:
  #     matrix:
  #       repo: ["khareRajshree/gobrick"]

  #   steps:
  #     - name: Trigger Dell Packages Update of ${{ matrix.repo }}
  #       uses: peter-evans/repository-dispatch@v3
  #       with:
  #         token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
  #         repository: ${{ matrix.repo }}
  #         event-type: latest-released-libraries
  #         client-payload: |
  #           {
  #             "ref": "${{ github.ref }}",
  #             "sha": "${{ github.sha }}"
  #           }

  release_dependent_repo:
    name: Release gobrick
    runs-on: ubuntu-latest
    needs: [release_independent_repos, update_dependencies]
    strategy:
      matrix:
        repo: ["khareRajshree/gobrick"]
    steps:
      - name: Trigger Release of ${{ matrix.repo }}
        uses: peter-evans/repository-dispatch@v3
        with:
          token: ${{ secrets.PERSONAL_ACCESS_TOKEN }}
          repository: ${{ matrix.repo }}
          event-type: release-go-libs
          client-payload: |
            { 
              "ref": "${{ github.ref }}", 
              "sha": "${{ github.sha }}"
            }
